- .travis.yml
- neuralmonkey/bidirectional_rnn_layer.py
- neuralmonkey/cells/noisy_gru_cell.py
- neuralmonkey/cells/pervasive_dropout_wrapper.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoding_function.py
- neuralmonkey/encoders/cnn_encoder.py
- neuralmonkey/encoders/sentence_encoder.py
- neuralmonkey/runners/perplexity_runner.py
> Upgrade to Tensorflow 0.9.0

- examples/language_model.ini
- neuralmonkey/decoders/decoder.py
- neuralmonkey/runners/perplexity_runner.py
Besides updating the language model example INI and PerplexityRunner, this also adds cross_entropies op to the decoder.
> Language model example

- neuralmonkey/train.py
> Relativize root of the neuralmonkey

- neuralmonkey/learning_utils.py
- neuralmonkey/train.py
minor things: randseed hardcoded, device placement, GPU memory usage
> For easier debugging

- .travis.yml
- neuralmonkey/encoders/sentence_encoder.py
- tests/data/train.tc.de
- tests/data/train.tc.en
- tests/data/val.tc.de
- tests/data/val.tc.en
- tests/tests_run.sh
> Dynamic rnn

- docs/source/features.rst
- docs/source/index.rst
- docs/source/tutorial.rst
Added parts into the documentation. No changes in the code
> Documentation

- neuralmonkey/decoders/decoder.py
- neuralmonkey/trainers/generic_trainer.py
> Enable and refactor image summaries

- neuralmonkey/trainers/generic_trainer.py
The trainer was probably more memory demanding because it was computing the gradients of the loss and regularization separately and then summing the up.
@tomkocmi, please chceck how the memory requirements of your experiments change in with this branch.
> Do as much gradients at once as possible in trainer

- neuralmonkey/learning_utils.py
Is this the correct approach of solving issues? And direct push should be only for bugs and docs?
I am sorry for reformatting whole file (I really wonder who designed PEP8, it doesn't seem ideologically consistent to me if this reformatting is also possible).
> Solving issue #113

- tests/doclint_run.sh
- tests/lint_run.sh
- tests/pycodestyle_run.sh
- tests/pydocstyle_run.sh
- tests/tests_run.sh
Sometimes, it may not be clear that the tests succeeded or failed (especially in case of pylint, you may have overlooked the error messages, get score 10.0 and still not pass the test). To avoid this, this PR introduces an explicit message in case pylint fails and control message if otherwise silent tests pass.
> Messages at the end of tests

- neuralmonkey/config/builder.py
- neuralmonkey/config/config_builder.py
- neuralmonkey/config/configuration.py
- neuralmonkey/config/parsing.py
- neuralmonkey/run.py
- neuralmonkey/server.py
- neuralmonkey/train.py
- tests/bahdanau.ini
- tests/bpe.ini
- tests/factored.ini
- tests/small-beam.ini
- tests/small.ini
- tests/test_data.ini
- tests/test_ensemble_data.ini
- tests/vocab.ini
This PR finally separates parsing of the `.ini` file from building of the model. It also introduces quotes around strings in configuration, so it's a breaking change.
> Configuration: separate parsing from building

- scripts/tf_save_images.py
This is a script that allows to extract a series of images from a given image summary
> Add tf_save_images.py

- neuralmonkey/decoders/decoder.py
This PR adds a flag to the decoder that decides whether to put attention from time step `t-1` to the input of the decoder in time step `t` jointly with the previously decoded token.
> Flag for attention on decoder's input

- neuralmonkey/decoders/decoder.py
This PR makes configurable whether the Decoder should use LSTM or GRU recurrent cell.
> Configurable RNN cell in decoder

- neuralmonkey/learning_utils.py
- neuralmonkey/tf_manager.py
- neuralmonkey/tf_utils.py
Runs nvidia-smi and reports a compact string of each GPU's memusage.
Could be improved by filtering for CUDA_VISIBLE_DEVICES.
> report GPU memory usage

- .readthedocs-conda.yml
- docs/source/dataset_creation.svg
- docs/source/model_workflow.svg
- docs/source/overview.rst
> Package Overview

- neuralmonkey/logbook/index.html
- neuralmonkey/logbook/logbook.js
- neuralmonkey/logbook/logbook.py
- neuralmonkey/logbook/style.css
This PR adds buttons for changing font size (now we have very long lines in the logs) and prepares toggling the left menu which I was too lazy to debug properly.
> Font zooming in logbook

- neuralmonkey/decoders/decoder.py.~master~
- neuralmonkey/learning_utils.py
- neuralmonkey/trainers/generic_trainer.py
This PR introduces computing  of total number of parameters being optimized in a trainer. There are reported in the log at the beginning of the training loop.
It resolves #257.
> Report number of paramters trained by trainer.

- examples/language_model.ini
- tests/vocab.ini
> use correct vocabulary initialization

- README.md
- docs/source/install.rst
installation with virtualenv
ještě přidám drobný změny do instalačního rst
EDIT: http://neural-monkey.readthedocs.io/en/readme_changes/install.html
> Installation documentation changes

- neuralmonkey/config/builder.py
- neuralmonkey/config/parsing.py
This makes the configuration parsing and building deterministic.
> make configuration deterministic

- neuralmonkey/learning_utils.py
- tests/post-edit.ini
* Fixes test post edit scenario (correct preprocessing, correct evaluator)
* Fixes nan ters and zero BLEUs in final APE testing phase
EDIT: correct preprocessing už jsem pushnul do mastera, to tady neni
> Fix postedit bug

- neuralmonkey/decoders/sequence_classifier.py
- neuralmonkey/nn/mlp.py
Simple bugfixes as dictated by @jindrahelcl .
> Fixes to SequenceClassifier

- neuralmonkey/readers/image_reader.py
This PR introduces an image reader that rescales the biggest possible middle rectangle of chosen ratio. It is a reimplementation of an algorithms that is used in [Caffe](http://caffe.berkeleyvision.org/).
> Reimplemented image reader from Caffe

- neuralmonkey/learning_utils.py
- neuralmonkey/trainers/generic_trainer.py
This PR introduces reporting of names, shapes and sizes of trainable variables.
> Trainable variables report

- neuralmonkey/config/configuration.py
- neuralmonkey/run.py
- neuralmonkey/train.py
> Refactoring configuration

- docs/source/development.rst
- docs/source/index.rst
- docs/source/internal_dev.rst
A preliminary version of developers guidelines. Feel free to praise, comment, or rant. :-)
You can check it out here:
http://neural-monkey.readthedocs.io/en/docs_guidelines/internal_dev.html
> Developers guidelines

- neuralmonkey/encoders/sentence_encoder.py
- neuralmonkey/encoders/sequence_cnn_encoder.py
- tests/classifier.ini
This PR introduces simple CNN for sequence classification as introduces by [Yoon Kim in _Convolutional Neural Networks for Sentence Classification_](http://emnlp2014.org/papers/pdf/EMNLP2014181.pdf).
> CNN for sequence classification

- neuralmonkey/config/builder.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoding_function.py
- neuralmonkey/evaluators/accuracy.py
- neuralmonkey/evaluators/average.py
- neuralmonkey/evaluators/f1_bio.py
- neuralmonkey/evaluators/gleu.py
- neuralmonkey/evaluators/ter.py
- neuralmonkey/functions.py
- neuralmonkey/learning_utils.py
- neuralmonkey/logging.py
- neuralmonkey/model/model_part.py
- neuralmonkey/nn/mlp.py
- neuralmonkey/nn/noisy_gru_cell.py
- neuralmonkey/nn/pervasive_dropout_wrapper.py
Pár nesystematicky doplněných anotací.
> různé anotace

- neuralmonkey/learning_utils.py
- neuralmonkey/runners/representation_runner.py
- tests/bahdanau.ini
This PR introduces a runner that is supposed to print out representation learned by a encoder.
> Runner for printing out encoder hidden states

- tests/tests_run.sh
This way we will know which code causes the segfault.
> Set PYTHONFAULTHANDLER in tests_run.sh

- neuralmonkey/run.py
I believe this may solve #308.
> run with batch size

- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sentence_encoder.py
- neuralmonkey/nn/highway.py
- neuralmonkey/tests/test_encoders_init.py
- tests/small_sent_cnn.ini
- tests/tests_run.sh
- Encoder architecture from article "https://arxiv.org/pdf/1610.03017.pdf"
- Highway network layer implementation from "https://arxiv.org/pdf/1505.00387.pdf"
- initialization unit tests for the encoder
> Conv rnn encoder

- neuralmonkey/learning_utils.py
Issue a warning if the lengths of the output series don't match the length of the dataset.
> Check output series lengths

- scripts/speech_features.py
This script precomputes speech features for a given set of audio files and saves them as a list of NumPy arrays.
> Add scripts/speech_features.py

- neuralmonkey/readers/string_vector_reader.py
- neuralmonkey/tests/test_readers.py
Reader that loads numerical data from a text file. Line by line, tokens separated by whitespace. Optionally, it can check for a given number of columns.
> String Vector Reader

- neuralmonkey/checking.py
- neuralmonkey/decoders/beam_search_decoder.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/learning_utils.py
- neuralmonkey/runners/beamsearch_runner.py
- tests/beamsearch.ini
- tests/tests_run.sh
In-graph implementation of beam search for batch size 1, inspired by google/seq2seq.
> In-graph beam search

- neuralmonkey/processors/bpe.py
> Configurable encoding of BPE merge files

- neuralmonkey/vocabulary.py
vocabulary raises warning when loading from nonexistent dataset series
fixes #386
> Vocabulary checks for nonexistent series

- neuralmonkey/dataset.py
- neuralmonkey/tests/test_dataset.py
> Lazy dataset check for file existence

- neuralmonkey/runners/logits_runner.py
- tests/classifier.ini
This PR introduces a runner that produces logits or a normalized distribution from a decoder (i.e., currently a recurrent decoder or a classifier) unlike the greedy runner which produces the argmax of the distributions.
> Runner outputing logits or distribution

- neuralmonkey/learning_utils.py
- tests/labeler.ini
During development I often do not know how long will the period be, but I usually know how long will it be running. Another importance is when experimenting with multiple tasks and datasets where some tasks have much shorter period.
> Timed validation

- neuralmonkey/learning_utils.py
- neuralmonkey/model/model_part.py
When storing global_variables, also optimizer variables are stored and then when I want to apply modelpart initialization for only one of the parts and the rest of the model was changes, it breaks.
I have tried to find where the saving is happening but I didn't find any place in source codes.
> Storing modelparts

- neuralmonkey/learning_utils.py
- neuralmonkey/logging.py
The test will need to be modified so it wouldn't warn on them. Any suggestions to that or code?
> Adding logging of time consumption

- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoders/output_projection.py
- neuralmonkey/decoders/sequence_classifier.py
- neuralmonkey/decoders/sequence_labeler.py
- neuralmonkey/encoders/cnn_encoder.py
- neuralmonkey/encoders/factored_encoder.py
- neuralmonkey/encoders/raw_rnn_encoder.py
- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sentence_encoder.py
- neuralmonkey/encoders/sequence_cnn_encoder.py
- neuralmonkey/nn/mlp.py
- neuralmonkey/nn/projection.py
- neuralmonkey/nn/utils.py
- neuralmonkey/tests/test_nn_utils.py
Please check it thoroughly, even that test are running I don't want to break NM.
> Dropout cleanup

- neuralmonkey/processors/editops.py
This PR allows to apply additional series-level post-processing on results on sentence-level postprocessing. For instance it allows to un-bpe a series that is a result of applying edit operations on a text.
> Editops fixes

- neuralmonkey/encoders/attentive.py
- neuralmonkey/encoders/numpy_encoder.py
- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sentence_encoder.py
- neuralmonkey/model/model_part.py
- neuralmonkey/tests/test_encoders_init.py
- neuralmonkey/tests/test_nn_utils.py
- tests/unit-tests_run.sh
> Unit tests fix

- neuralmonkey/evaluators/accuracy.py
- neuralmonkey/tests/test_eval_wrappers.py
Replaces the accuracy evaluator part of #437
> Sequence-level accuracy evaluator

- neuralmonkey/logging.py
- neuralmonkey/train.py
Reverts c917177 and adds output direcory to the experiment "header".
> Output directory goes to log

- neuralmonkey/encoders/imagenet_encoder.py
- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sequence_cnn_encoder.py
- tests/captioning.ini
Refactor of ImageNetEncoder, SequenceCNNEncoder and SentenceCNNEncoder using the `@tensor` annotation.
> CNN encoders refactor

- neuralmonkey/config/utils.py
- neuralmonkey/tests/test_vocabulary.py
- neuralmonkey/vocabulary.py
- tests/audio-classifier.ini
- tests/beamsearch.ini
- tests/classifier.ini
- tests/language-model.ini
- tests/regressor.ini
- tests/self-critical.ini
- tests/small.ini
- tests/vocab.ini
Separate vocabulary refactor.
Pickled loading scratched, wordlist loading introduced. 
Do not merge #466.
> Vocabulary refactor

- neuralmonkey/evaluators/chrf.py
see paper http://www.statmt.org/wmt15/pdf/WMT49.pdf
> implemented ChrF metric

- neuralmonkey/decoders/sequence_labeler.py
When I removed the tanh, the performance on both CNN lemmatizer and RNN tagger raised.
> Correction of labeler

- neuralmonkey/readers/image_reader.py
This PR generalizes options for re-scaling and cropping images while being loaded.
> Generalize image reader options

- neuralmonkey/readers/plain_text_reader.py
_csv.Error: field larger than field limit (131072)
> Avoiding csv limit

- neuralmonkey/decoders/decoder.py
I have done several experiments on places where to change linear layer with the nonlinear. Only significant improvement was with this change.
> improving performance of decoder

- neuralmonkey/runners/label_runner.py
fix to get labeler working in run script
> labeler fix

- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoders/output_projection.py
this commit changes the default behavior of the decoder. The output projection parameter
is now used and it may be either an output projection function or a tuple of output projection
function and an integer specifying the output size.
this can be achieved with higher order functions defined in the output_projection module.
For legacy settings, there are some functions in the output projection module defined.
There is still some cleaning to do in the module.
> Configurable output projection

- neuralmonkey/attention/__init__.py
- neuralmonkey/attention/base_attention.py
- neuralmonkey/attention/combination.py
- neuralmonkey/attention/coverage.py
- neuralmonkey/attention/feed_forward.py
- neuralmonkey/attention/scaled_dot_product.py
- neuralmonkey/encoders/imagenet_encoder.py
- tests/factored.ini
- tests/post-edit.ini
Scaled dot-product attention from Vaswani et al. (2017): https://arxiv.org/pdf/1706.03762.pdf
This pull request also include the multi-head attention generalization.
First, #536 should be merged (not necessarily, but favorably)
> Scaled dot-product attention

- neuralmonkey/vocabulary.py
> better truncating of the vocabulary

- neuralmonkey/encoders/recurrent.py
This is useful for training low-dimensional "bottleneck representations".
> Add final state projection to encoder

- neuralmonkey/vocabulary.py
- tests/factored.ini
- tests/small_sent_cnn.ini
- tests/str.ini
> fixing bug in the vocabulary.truncate() method

- docs/source/machine_translation.rst
> Tutorial: how to resume training

- neuralmonkey/config/configuration.py
This PR enables calling `Configuration.load_file` multiple times in a row. Each call updates the configuration by adding or overriding sections in the config dict.
> Enable incremental config file loading

- bin/neuralmonkey-server
- neuralmonkey/server/server.html
- neuralmonkey/server/server.py
- neuralmonkey/server/static/server.css
- neuralmonkey/server/static/style.css
- neuralmonkey/server/templates/server.html
- tests/tests_run.sh
Updated neuralmonkey-server style and behavior.
> Server update

- requirements-gpu.txt
- requirements.txt
> Upgrade to Tensorflow 1.4

- neuralmonkey/attention/combination.py
- neuralmonkey/attention/feed_forward.py
- neuralmonkey/decoders/ctc_decoder.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoders/encoder_projection.py
- neuralmonkey/decoders/output_projection.py
- neuralmonkey/decoders/sequence_labeler.py
- neuralmonkey/encoders/facebook_conv.py
- neuralmonkey/encoders/numpy_encoder.py
- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sequence_cnn_encoder.py
- neuralmonkey/model/sequence.py
- neuralmonkey/nn/highway.py
- neuralmonkey/nn/ortho_gru_cell.py
Making initialization great again
> Initialization

- neuralmonkey/config/builder.py
- scripts/build_config.py
This can be useful for debugging or hacking models.
> Generate code from ini file

- neuralmonkey/encoders/attentive.py
- neuralmonkey/encoders/attentive_embedding.py
- neuralmonkey/runners/base_runner.py
- tests/classifier.ini
Based on ["A Structured Self-attentive Sentence Embedding"](https://arxiv.org/abs/1703.03130).
> Attentive encoder

- neuralmonkey/encoders/__init__.py
- neuralmonkey/encoders/cnn_encoder.py
- neuralmonkey/readers/image_reader.py
- neuralmonkey/trainers/generic_trainer.py
- tests/str.ini
This PR introduces residual connection into a CNN which requires a bit more complicated way of configuration as well. Moreover, it contains a RNN applied on top of sliced output of CNN that I use for OCR.
> Residual connection to CNN, encoder with RNN on top of CNN

- neuralmonkey/config/parsing.py
- neuralmonkey/dataset.py
- neuralmonkey/decoders/encoder_projection.py
- neuralmonkey/evaluators/f1_bio.py
- neuralmonkey/processors/alignment.py
- tests/lint_run.sh
Few standard plugins are added to pylint:
* checking fro deprecated builtin function
* checking for `else: if` which should be `elif`
* check for redefining variable type (should be already covered by mypy)
* check for conditions `something == ""` and `something != ""`
> Add few standard plugins to pylint

- neuralmonkey/encoders/cnn_encoder.py
* I accidentally banned saving checkpoint because I confused the encoder with ImageNet encoder
* there was an assertion that expected the previous way of layers configuration
* convolution was returning mask instead of its real output
> Fix bugs introduced by #625

- docs/source/configuration.rst
- neuralmonkey/learning_utils.py
- neuralmonkey/tf_manager.py
- neuralmonkey/tf_utils.py
> Removing the report_gpu_consumption feature

- neuralmonkey/run.py
> Added condition for the variables config in run INI

- neuralmonkey/dataset.py
- neuralmonkey/tests/test_dataset.py
- neuralmonkey/train.py
This PR fixes `LazyDataset` by using a generator expression instead of a list comprehension.
> Make LazyDataset lazy again

- neuralmonkey/dataset.py
- neuralmonkey/tests/test_dataset.py
- tests/data/val10.part1.tc.en
- tests/data/val10.part2.tc.en
- tests/test_data.ini
> Support filename patterns in dataset configuration

- neuralmonkey/run.py
> Evaluation is optional in run script.

- neuralmonkey/vocabulary.py
> Nicer sampling vocabulary log

- neuralmonkey/learning_utils.py
> Nicer validation log of numpy arrays.

- neuralmonkey/dataset.py
- Make `Dataset` accept `preprocessors` (like `LazyDataset`).
- Allow for multiple steps of preprocessing in `LazyDataset`.
>  More consistent datasets

- neuralmonkey/config/parsing.py
- tests/small.ini
- tests/tests_run.sh
When an undefined variable is referenced in the config file, the config parser will look for it in the environment.
> Accessing environment variables

- neuralmonkey/checkpython.py
- neuralmonkey/logbook/logbook.py
- neuralmonkey/run.py
- neuralmonkey/server/server.py
- neuralmonkey/train.py
This might prevent some cryptic errors when user tries to run NM with python3.4.
> check python interpreter version

- neuralmonkey/vocabulary.py
> truncate vocabulary

- neuralmonkey/attention/combination.py
- neuralmonkey/attention/coverage.py
- neuralmonkey/config/builder.py
- neuralmonkey/dataset.py
- neuralmonkey/decoders/beam_search_decoder.py
- neuralmonkey/encoders/imagenet_encoder.py
- neuralmonkey/encoders/pooling.py
- neuralmonkey/experiment.py
- neuralmonkey/learning_utils.py
- neuralmonkey/processors/editops.py
- neuralmonkey/readers/plain_text_reader.py
- neuralmonkey/runners/beamsearch_runner.py
- neuralmonkey/vocabulary.py
For new version of pycodestyle
> Pycodestyle fix

- neuralmonkey/evaluators/bleu.py
Multiple references are stored in a single data series and separated by a special configurable token.
> BLEU evaluator can use multiple references

- neuralmonkey/decoders/autoregressive.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoders/transformer.py
- tests/bahdanau.ini
> Supress <unk>

- scripts/import_transformer.1.2.9.py
- scripts/import_transformer.1.3.2.py
The import script was not updated for the changes in the API.
> Fix Transformer import

- neuralmonkey/encoders/numpy_stateful_filler.py
This PR adds an optional linear projection of the loaded spacial states in spatial filler.
> Optinal projection in stateful filler

- neuralmonkey/server/server.py
This PR allows the server to respond alos with outputs of TensorRunner and RepresentationRunner which are numpy arrays which needs  to be converted to lists before they are serialized.
> Server can now respond tensors

- neuralmonkey/evaluators/__init__.py
- neuralmonkey/evaluators/rouge.py
- requirements-gpu.txt
- requirements.txt
- tests/bahdanau.ini
This PR adds a ROUGE score evaluator for text summarization.
It uses a third-party library (https://github.com/pltrdy/rouge) with Apache 2.0 licence.
> Rouge score

- neuralmonkey/attention/base_attention.py
- neuralmonkey/decoders/autoregressive.py
- neuralmonkey/decoders/beam_search_decoder.py
- neuralmonkey/decoders/classifier.py
- neuralmonkey/decoders/ctc_decoder.py
- neuralmonkey/decoders/sequence_labeler.py
- neuralmonkey/decoders/sequence_regressor.py
- neuralmonkey/decoders/word_alignment_decoder.py
- neuralmonkey/encoders/attentive.py
- neuralmonkey/encoders/cnn_encoder.py
- neuralmonkey/encoders/facebook_conv.py
- neuralmonkey/encoders/imagenet_encoder.py
- neuralmonkey/encoders/numpy_stateful_filler.py
- neuralmonkey/encoders/pooling.py
- neuralmonkey/encoders/raw_rnn_encoder.py
- neuralmonkey/encoders/recurrent.py
- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sequence_cnn_encoder.py
- neuralmonkey/encoders/transformer.py
- neuralmonkey/model/model_part.py
- neuralmonkey/model/sequence.py
now, all model parts have self.train_mode and self.batch_size
filled appropriately.
> default feed dict implementation moved to model part

- neuralmonkey/decoders/transformer.py
Fixed wrong indentation in the transformer decoder.
> transformer_decoder: sampling bugfix

- neuralmonkey/decoders/autoregressive.py
> supress unk fix. 

- neuralmonkey/attention/combination.py
- neuralmonkey/attention/feed_forward.py
- neuralmonkey/attention/scaled_dot_product.py
- neuralmonkey/decoders/autoregressive.py
- neuralmonkey/decoders/ctc_decoder.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/decoders/encoder_projection.py
- neuralmonkey/decoders/output_projection.py
- neuralmonkey/decoders/sequence_labeler.py
- neuralmonkey/decoders/transformer.py
- neuralmonkey/encoders/facebook_conv.py
- neuralmonkey/encoders/recurrent.py
- neuralmonkey/encoders/sentence_cnn_encoder.py
- neuralmonkey/encoders/sequence_cnn_encoder.py
- neuralmonkey/encoders/transformer.py
- neuralmonkey/model/sequence.py
- neuralmonkey/nn/highway.py
- neuralmonkey/nn/ortho_gru_cell.py
This is what we've done in the `wmt18-devel` branch to the initializers.
> Initializers

- neuralmonkey/attention/scaled_dot_product.py
- neuralmonkey/decoders/decoder.py
- neuralmonkey/encoders/numpy_stateful_filler.py
- neuralmonkey/readers/numpy_reader.py
- neuralmonkey/runners/__init__.py
- neuralmonkey/runners/tensor_runner.py
- tests/bahdanau.ini
See commit messages, should be straigtforward.
> Minor refactoring commits

- neuralmonkey/dataset/dataset.py
- neuralmonkey/dataset/helpers.py
- neuralmonkey/dataset/lazy_dataset.py
A little messy, but behavior-fixing pull request.
> Fix lazy dataset with preprocessors

- neuralmonkey/encoders/recurrent.py
- tests/nematus.ini
Seems pretty straightforward. Closes #706
> recurrent: residual connections in rnn_layer

- neuralmonkey/run.py
I would like to have this merged for the MTM lab so that we can easily load a dataset from a Jupyter notebook.
> Function for test config loading

- neuralmonkey/experiment.py
Prevent appending `.cont-...` to variable file prefix.
> Fix variable loading for continued experiments

- neuralmonkey/model/sequence.py
The metadata path needs to be relative to the model directory.
> Fix embedding metadata path

- neuralmonkey/learning_utils.py
- neuralmonkey/trainers/delayed_update_trainer.py
- neuralmonkey/trainers/generic_trainer.py
- tests/labeler.ini
- tests/transformer.ini
I'm opening a new PR because the other one got sucked into a different branch.
> Delayed update trainer

- neuralmonkey/model/sequence.py
This PR adds a flag that allows sequence not to be trainable, e.g. when using pre-trained embeddings.
> Sequence has trainable option

- neuralmonkey/decoders/autoregressive.py
- neuralmonkey/trainers/rl_trainer.py
Autoregressive.decoding_loop now returns whole LoopState instead of a subset of LoopState properties
> Decoding loop refactor

- neuralmonkey/runners/beamsearch_runner.py
- tests/pydocstyle_requirements.txt
because there is a bug in 4.0.0
> upgrading code to new scipy, fixing pydocstyle on 3.0.0 
